name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - elasticsearch:8.2.0
          - elasticsearch:7.13.2
          - elasticsearch:6.8.16
          - elasticsearch:5.6.16
          - elasticsearch:2.4.6
          - elasticsearch:1.7.3
          - opensearch:1.3.3
          - opensearch:2.0.1
    steps:
      - uses: actions/checkout@v3
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - uses: ./.
        with:
          stack: ${{ matrix.stack }}
          port: 9200
      - name: Wait for service
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:9200/'
          responseCode: '200'
          timeout: 20000
          interval: 500
      - run: curl -s localhost:9200


