name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - elasticsearch:8.2.0
          - elasticsearch:7.13.2
          - elasticsearch:6.8.16
          - elasticsearch:5.6.16
          - elasticsearch:2.4.6
          - elasticsearch:1.7.3
          - opensearch:1.3.3
          - opensearch:2.0.1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.
        with:
          stack: ${{ matrix.stack }}
          port: 9200
      - run: curl -s localhost:9200


